numbers_to_learn = {
    '1': 'un',
    '2': 'deux',
    '3': 'trois',
    '4': 'quatre',
    '5': 'cinq',
    '6': 'six',
    '7': 'sept',
    '8': 'huit',
    '9': 'neuf',
    '10': 'dix',
    '11': 'onze',
    '12': 'douze',
    '13': 'treize',
    '14': 'quatorze',
    '15': 'quinze',
    '16': 'seize',
    '17': 'dix-sept',
    '18': 'dix-huit',
    '19': 'dix-neuf',
    '20': 'vingt',
    '21': 'vingt-et-un',
    '22': 'vingt-deux',
    '23': 'vingt-trois',
    '24': 'vingt-quatre',
    '25': 'vingt-cinq',
    '26': 'vingt-six',
    '27': 'vingt-sept',
    '28': 'vingt-huit',
    '29': 'vingt-neuf',
    '30': 'trente',
    '31': 'trente et un',
    '32': 'trente-deux',
    '33': 'trente-trois',
    '34': 'trente-quatre',
    '35': 'trente-cinq',
    '36': 'trente-six',
    '37': 'trente-sept',
    '38': 'trente-huit',
    '39': 'trente-neuf',
    '40': 'quarante',
    '41': 'quarante et un',
    '42': 'quarante-deux',
    '43': 'quarante-trois',
    '44': 'quarante-quatre',
    '45': 'quarante-cinq',
    '46': 'quarante-six',
    '47': 'quarante-sept',
    '48': 'quarante-huit',
    '49': 'quarante-neuf',
    '50': 'cinquante'
}

greetings_to_learn = {
    "Bonjour": "Hello/Good morning",
    "Bonsoir": "Good evening",
    "Bonne nuit": "Good night",
    "Au revoir": "Goodbye",
    "Salut": "Hi/Bye (informal)",
    "Comment ça va?": "How are you?",
    "Ça va bien, et toi?": "I'm fine, and you? (informal)",
    "Ça va bien, et vous?": "I'm fine, and you? (formal)",
    "Pas mal, merci": "Not bad, thank you",
    "Très bien, merci": "Very well, thank you",
    "Comment vas-tu?": "How are you? (informal)",
    "Comment allez-vous?": "How are you? (formal)",
    "Quoi de neuf?": "What's new?",
    "Rien de spécial": "Nothing much",
    "À plus tard": "See you later",
    "À demain": "See you tomorrow",
    "Je suis désolé(e)": "I'm sorry",
    "Excusez-moi": "Excuse me",
    "Pardon": "Sorry",
    "S'il te plaît": "Please (informal)",
    "S'il vous plaît": "Please (formal)",
    "Merci": "Thank you",
    "Merci beaucoup": "Thank you very much",
    "De rien": "You're welcome",
    "À bientôt": "See you soon"
}


nouns_to_learn = {
    "chat": "cat",
    "chien": "dog",
    "maison": "house",
    "voiture": "car",
    "livre": "book",
    "pomme": "apple",
    "arbre": "tree",
    "fleur": "flower",
    "chaise": "chair",
    "table": "table",
    "soleil": "sun",
    "lune": "moon",
    "étoile": "star",
    "ciel": "sky",
    "mer": "sea",
    "lac": "lake",
    "rivière": "river",
    "montagne": "mountain",
    "forêt": "forest",
    "chemin": "path",
    "parc": "park",
    "jardin": "garden",
    "fleur": "flower",
    "arbre": "tree",
    "herbe": "grass",
    "oiseau": "bird",
    "poisson": "fish",
    "insecte": "insect",
    "animal": "animal",
    "frère": "brother",
    "sœur": "sister",
    "mère": "mother",
    "père": "father",
    "ami": "friend",
    "amie": "friend (f)",
    "professeur": "teacher",
    "étudiant": "student",
    "enfant": "child",
    "adulte": "adult",
    "personne": "person",
    "ville": "city",
    "pays": "country",
}


pronouns_to_learn = {
    "je": "I",
    "tu": "you (singular, informal)",
    "il": "he",
    "elle": "she",
    "on": "one/we/people",
    "nous": "we",
    "vous": "you (plural, formal)",
    "ils": "they (masculine)",
    "elles": "they (feminine)"
}


common_phrases_to_learn = {
    "Je suis désolé": "I am sorry",
    "Pouvez-vous m'aider?": "Can you help me?",
    "Où est la salle de bain?": "Where is the bathroom?",
    "Combien ça coûte?": "How much does it cost?",
    "Je ne comprends pas": "I do not understand",
    "Parlez-vous anglais?": "Do you speak English?",
    "Puis-je avoir le menu?": "May I have the menu?",
    "Quelle heure est-il?": "What time is it?",
    "Je voudrais ceci": "I would like this",
    "Pouvez-vous répéter ça?": "Can you repeat that?",
    "Je ne sais pas": "I don't know",
    "À quelle distance est-ce?": "How far is it?",
    "Où puis-je acheter des billets?": "Where can I buy tickets?",
    "Avez-vous des recommandations?": "Do you have any recommendations?",
    "Pouvez-vous parler plus lentement?": "Can you speak slower?",
    "Je cherche cette adresse": "I am looking for this address",
    "Pouvez-vous me dire comment aller à?": "Can you tell me how to get to?",
    "Quel est le meilleur chemin pour?": "What is the best way to?",
    "Pouvez-vous me montrer sur la carte?": "Can you show me on the map?",
    "Quel est le prix de ceci?": "What is the price of this?"
}